### ISSUE TITLE
push file some times fails

### ISSUE THREAD

**Issue by prife** [prife/goadb#1]
push file will be deleted when use cmd/adb

**Comment by prife** [comment]
fixed https://github.com/prife/goadb/commit/a2a416f168a0c920b2b498dd51434079747d14e0

**Comment by felixruan** [comment]
@prife push命令显示传输完成，但是手机（Android10）并没有文件
# go build cmd/adb/main.go
# ./main.exe push -p D:\sonic.txt /data/local/tmp/sonic.txt
529 B / 529 B [============================================================================================================================================================================================] 100.00% 1.12 MiB/s 0s 
926607 B/s (529 bytes in 570.9µs)

# adb shell ls /data/local/tmp/ 为空
